server:
  port: ${IDENTITY_SERVICE_PORT:8081}

spring:
  application:
    name: identity-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASS:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${IDENTITY_DB:identity_db}?authSource=${MONGO_AUTH_SOURCE:admin}

app:
  mongo:
    database: ${ACCESS_CONTROL_DB:access_control_db}
  jwt:
    secret: ${JWT_SECRET:12345678901234567890123456789012}
    access-token-expiration-seconds: ${JWT_EXPIRATION:3600}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.identity_service]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true