server:
  port: ${VISIT_CALENDAR_SERVICE_PORT:8086}

spring:
  application:
    name: visit-calendar-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASS:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${VISIT_CALENDAR_DB:visit_calendar_db}?authSource=${MONGO_AUTH_SOURCE:admin}

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.visit_calendar_service]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true

user:
  service:
    url: http://localhost:8081  # Ajusta según el puerto real de user-service

person:
  service:
    url: http://localhost:8084  # Ajusta según el puerto real de person-service

property:
  service:
    url: http://localhost:8085  # Ajusta según el puerto real de property-service

notification:
  service:
    url: http://localhost:8083  # Puerto del notification-service