server:
  port: 8086

spring:
  application:
    name: visit-calendar-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/inmobiliaria_db?authSource=admin

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.visit_calendar_service]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

user:
  service:
    url: http://localhost:8081  # Ajusta según el puerto real de user-service

person:
  service:
    url: http://localhost:8084  # Ajusta según el puerto real de person-service

notification:
  service:
    url: http://localhost:8083  # Puerto del notification-service