server:
  port: ${USER_SERVICE_PORT:8084}

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASS:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${USER_DB:user_db}?authSource=${MONGO_AUTH_SOURCE:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.user_service]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true