server:
  port: 8085

spring:
  application:
    name: property-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/inmobiliaria_db?authSource=admin
  cloud:
    config:
      enabled: false

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.property_service]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: properties
  images:
    bucket: property-images
  documents:
    bucket: documents
  presigned:
    expiry-minutes: 15